version: "2"

services:
  urlfilter-fake-only:
    image: golang:latest
    volumes:
      - ..:/go/src/github.com/tmortimer/urlfilter
    working_dir: /go/src/github.com/tmortimer/urlfilter
    ports:
      - 8080:8080
    command: >
      sh -c "go get
             go run urlfilter.go --config=configs/fake-only.json"
